### ISSUE TITLE
官方liqi.json文件有部分错误

### ISSUE THREAD

**Issue by hyskylord** [takayama-lily/mjsoul#4]
最近发现由于不知名原因，使用官方提供的liqi.json文件无法解析部分协议，经过观察发现接收到的内容和liqi.json文件描述不符。
目前发现的无法解析的协议：.lq.Lobby.fetchFriendList，.lq.Lobby.fetchShopInfo，.lq.Lobby.fetchCharacterInfo；解决方法未知
解析有误的协议：.lq.Lobby.ResMonthTicketInfo，.lq.Lobby.fetchServerSettings，研究后发现官方提供的liqi.json文件中field id有误。

例：        "ResMonthTicketInfo": {
          "fields": {
            "error": {
              "type": "Error",
              "id": 2
            },
            "month_ticket_info": {
              "rule": "repeated",
              "type": "MonthTicketInfo",
              "id": 1
            }
          }
        },

正确的协议应为：        "ResMonthTicketInfo": {
          "fields": {
            "error": {
              "type": "Error",
              "id": 1
            },
            "month_ticket_info": {
              "rule": "repeated",
              "type": "MonthTicketInfo",
              "id": 2
            }
          }
        },

**Comment by takayama-lily** [comment]
目前的liqi.json可能有点旧了。你比较过浏览器里最新的liqi.json吗，是否也有问题？
如果最新的没问题替换掉应该就好了

**Comment by hyskylord** [comment]
解决了，感谢。
